// lib/core/services/premium_service.dart
//
// Single source of truth for the user's premium tier.
// Wraps RevenueCat purchases_flutter SDK.
//
// Tiers:
//   - free    : default, no subscription
//   - plus    : $2/mo — limited images, 200 questions/mo, no ads
//   - pro     : $5/mo — unlimited questions, video posts, Focus Mode
//
// RevenueCat product IDs (set these up in RevenueCat dashboard):
//   edul_plus_monthly   → $2/mo
//   edul_pro_monthly    → $5/mo
//
// Entitlement IDs in RevenueCat dashboard:
//   plus   → granted by edul_plus_monthly
//   pro    → granted by edul_pro_monthly

import 'package:purchases_flutter/purchases_flutter.dart';
import 'package:flutter/foundation.dart';

enum PremiumTier { free, plus, pro }

class PremiumService {
  PremiumService._();

  // ── Launch kill-switch ────────────────────────────────────────────────────
  // Set this back to `false` once you're ready to start monetizing/gating.
  // While `true`, every user is treated as Pro tier everywhere in the app —
  // no paywalls, no caps — regardless of what RevenueCat actually reports.
  // RevenueCat purchase flow itself is untouched, so testing real purchases
  // still works; this only affects what tier the REST of the app *sees*.
  static const bool premiumDisabledForLaunch = true;

  // ── RevenueCat product / entitlement IDs ─────────────────────────────────
  static const String _plusEntitlement = 'plus';
  static const String _proEntitlement  = 'pro';
  static const String _plusProductId   = 'edul_plus_monthly';
  static const String _proProductId    = 'edul_pro_monthly';

  // ── Cached tier (updated on each checkTier call) ──────────────────────────
  static PremiumTier _cachedTier = PremiumTier.free;
  static PremiumTier get currentTier =>
      premiumDisabledForLaunch ? PremiumTier.pro : _cachedTier;

  // ── Convenience getters ───────────────────────────────────────────────────
  static bool get isFree =>
      !premiumDisabledForLaunch && _cachedTier == PremiumTier.free;
  static bool get isPlus =>
      premiumDisabledForLaunch ||
      _cachedTier == PremiumTier.plus ||
      _cachedTier == PremiumTier.pro;
  static bool get isPro =>
      premiumDisabledForLaunch || _cachedTier == PremiumTier.pro;
  // ── Real tier (ignores the launch kill-switch) ────────────────────────────
  // Use this — not isFree/isPlus/isPro — for anything gating actual paid
  // API usage (e.g. AI Tutor). Keeps a real cost lid on even while
  // premiumDisabledForLaunch unlocks everything else for launch.
  static bool get isRealFree => _cachedTier == PremiumTier.free;

  // ── Limits ────────────────────────────────────────────────────────────────

  // Focus Mode: number of sessions
  static int get focusSessionsAllowed =>
      isPro ? 999999 : isPlus ? 5 : 3; // pro=unlimited, plus=5/mo, free=3 total

  // Focus Mode: cancellations allowed
  // Pro: 5/week, Plus: 5/month, Free: 3 total (same as sessions)
  static int get focusCancellationsAllowed =>
      isPro ? 5 : isPlus ? 5 : 3;

  // Focus cancellation window
  static String get focusCancellationWindow =>
      isPro ? 'week' : isPlus ? 'month' : 'total';

  // Learning map ads
  static bool get showLearningMapAds => isFree;

  // AI Tutor text session limit (minutes per day, 0 = unlimited)
  static int get tutorTextMinutesPerDay => isFree ? 20 : 0;
  static bool get tutorHasTimeLimit => isFree;

  // Auto-generated PDFs per month
  static int get autoGeneratedPdfsPerMonth =>
      isPro ? 999999 : isPlus ? 20 : 5;

  // Ebook/PDF access per month
  static int get ebookAccessPerMonth => isPro ? 999999 : 3;

  // Social image posts per month
  static int get socialImagePostsPerMonth =>
      isPro ? 30 : isPlus ? 10 : 0;

  // Images per social post
  static int get imagesPerSocialPost =>
      isPro ? 5 : isPlus ? 3 : 0;

  // Social video posts per month (Pro only)
  static int get socialVideoPostsPerMonth => isPro ? 20 : 0;

  // AI Tutor PDF uploads per month (to AI Tutor, not auto-gen)
  static int get tutorPdfUploadsPerMonth =>
      isPro ? 999999 : isPlus ? 10 : 1;

  // AI Tutor image uploads per month
  static int get tutorImageUploadsPerMonth =>
      isPro ? 999999 : isPlus ? 3 : 0;

  // Quiz questions per month cap
  static int get monthlyQuizCap => isPro ? 999999 : isPlus ? 200 : 20;

  // ── Init ──────────────────────────────────────────────────────────────────
  static Future<void> initialize() async {
    if (kIsWeb) return;

    final apiKey = defaultTargetPlatform == TargetPlatform.iOS
        ? 'appl_test_wpFQGsnATmYwLcPqZcSSUpIxgZG' // TODO: still a placeholder -- swap when you have a real iOS key
        : 'goog_HQIERDHTYxErhXQEYQWLtUoNWBl';

    await Purchases.setLogLevel(LogLevel.error);
    await Purchases.configure(PurchasesConfiguration(apiKey));
    await checkTier();
  }

  // ── Check current tier from RevenueCat ───────────────────────────────────
  static Future<PremiumTier> checkTier() async {
    try {
      final info = await Purchases.getCustomerInfo();
      if (info.entitlements.active.containsKey(_proEntitlement)) {
        _cachedTier = PremiumTier.pro;
      } else if (info.entitlements.active.containsKey(_plusEntitlement)) {
        _cachedTier = PremiumTier.plus;
      } else {
        _cachedTier = PremiumTier.free;
      }
    } catch (_) {
      // Network error — keep cached tier
    }
    return _cachedTier;
  }

  // ── Fetch offerings (for paywall) ─────────────────────────────────────────
  static Future<Offerings?> getOfferings() async {
    try {
      return await Purchases.getOfferings();
    } catch (e) {
      // Rethrow instead of swallowing -- silently returning null here
      // meant the paywall's purchase button did visibly nothing on
      // failure, with no error shown at all.
      throw Exception('Could not load subscription plans: $e');
    }
  }

  // ── Purchase ──────────────────────────────────────────────────────────────
  static Future<PremiumTier?> purchasePlus() async =>
      _purchase(_plusProductId);

  static Future<PremiumTier?> purchasePro() async =>
      _purchase(_proProductId);

  static Future<PremiumTier?> _purchase(String productId) async {
    try {
      final offerings = await getOfferings();
      if (offerings == null || offerings.current == null) {
        throw Exception('No subscription plans are available right now.');
      }

      final packages = offerings.current!.availablePackages;
      if (packages.isEmpty) {
        throw Exception('No subscription plans are configured yet.');
      }
      final matching = packages.where((p) => p.storeProduct.identifier == productId);
      final package = matching.isNotEmpty ? matching.first : packages.first;

      final info = (await Purchases.purchase(PurchaseParams.package(package))).customerInfo;
      if (info.entitlements.active.containsKey(_proEntitlement)) {
        _cachedTier = PremiumTier.pro;
      } else if (info.entitlements.active.containsKey(_plusEntitlement)) {
        _cachedTier = PremiumTier.plus;
      } else {
        throw Exception('Purchase completed, but no matching entitlement was found.');
      }
      return _cachedTier;
    } on PurchasesErrorCode catch (e) {
      if (e == PurchasesErrorCode.purchaseCancelledError) return null;
      rethrow;
    }
  }

  // ── Restore purchases ─────────────────────────────────────────────────────
  static Future<PremiumTier> restorePurchases() async {
    try {
      final info = await Purchases.restorePurchases();
      if (info.entitlements.active.containsKey(_proEntitlement)) {
        _cachedTier = PremiumTier.pro;
      } else if (info.entitlements.active.containsKey(_plusEntitlement)) {
        _cachedTier = PremiumTier.plus;
      } else {
        _cachedTier = PremiumTier.free;
      }
    } catch (_) {}
    return _cachedTier;
  }
}