# Podfile
# CocoaPods documentation: https://guides.cocoapods.org/using/the-podfile.html

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_NOTIFICATIONS=1',
      ]
    end
  end
end

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join(
    File.dirname(__FILE__),
    'Flutter',
    'Generated.xcconfig',
  ), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

def flutter_version_name
  generated_version_file = File.expand_path(File.join(
    File.dirname(__FILE__),
    'Flutter',
    'flutter_export_environment.sh',
  ), __FILE__)
  unless File.exist?(generated_version_file)
    raise "#{generated_version_file} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_version_file) do |line|
    matches = line.match(/FLUTTER_BUILD_NUMBER\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_BUILD_NUMBER not found in #{generated_version_file}. Try deleting flutter_export_environment.sh, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
