// lib/features/auth/presentation/pages/splash_page.dart
//
// No visible UI of its own anymore -- the native splash (generated by
// flutter_native_splash) is the only splash screen that should ever
// be seen. This widget exists purely to run the auth-check/routing
// decision below and hand off directly to home/login/onboarding,
// with nothing shown in between. Its build() renders a blank,
// background-colored screen (not the old logo/tagline/spinner) so
// that even the brief moment before navigation completes looks like
// a seamless continuation of the native splash, not a second splash
// screen in its own right.

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../../../core/services/user_service.dart';

class SplashPage extends StatefulWidget {
  const SplashPage({super.key});
  @override
  State<SplashPage> createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {
  @override
  void initState() {
    super.initState();
    // No artificial delay -- runs as soon as this widget exists,
    // rather than the old fixed 1800ms hold that made this screen
    // feel like its own separate splash step.
    _navigate();
  }

  Future<void> _navigate() async {
    if (!mounted) return;
    try {
      final prefs = await SharedPreferences.getInstance();
      final hasOnboarded = prefs.getBool('has_onboarded') ?? false;
      var user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        // A failed/timed-out reload() does NOT mean the session is
        // actually invalid -- it just means we couldn't refresh their
        // profile data on this launch (network hiccup, slow connection,
        // etc). Signing them out here was far too aggressive: it turned
        // any transient reload failure into a real, destructive logout,
        // every single time it happened. Falling back to the cached
        // user instead matches the same fail-safe approach already used
        // in auth_bloc.dart's own startup check.
        try {
          await user.reload().timeout(const Duration(seconds: 5), onTimeout: () {});
          user = FirebaseAuth.instance.currentUser;
        } catch (e) {
          // Keep the cached user -- don't sign out over a reload failure.
        }
      }
      if (user != null) {
        // Already logged in -- always go straight home, regardless of
        // has_onboarded. Onboarding is only for someone who has never
        // signed in before; checking it first (as this used to) meant
        // anyone who ever tapped "Skip" (which never set the flag) got
        // sent through onboarding again on every single launch, even
        // fully logged in.
        try {
          await UserService.resetDailyIfNeeded().timeout(const Duration(seconds: 3), onTimeout: () {});
        } catch (_) {}
        if (mounted) context.go('/home');
      } else if (!hasOnboarded) {
        if (mounted) context.go('/onboarding');
      } else {
        if (mounted) context.go('/login');
      }
    } catch (e) {
      if (mounted) context.go('/login');
    }
  }

  @override
  Widget build(BuildContext context) {
    // Deliberately blank, and deliberately hard-coded white rather
    // than AppColors.background -- that getter switches to a near-
    // black dark-mode color at night, while the native splash (in
    // pubspec.yaml's flutter_native_splash config) is fixed white.
    // Using the dynamic color here would cause exactly the flash
    // this is meant to avoid, just at night instead of never.
    return const Scaffold(backgroundColor: Colors.white);
  }
}